// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpK0P0Xk2DFLdN8tzC1u5YQY5edwt667U',
    appId: '1:91542018746:web:76a2007b06237be5904083',
    messagingSenderId: '91542018746',
    projectId: 'alx-voyager',
    authDomain: 'alx-voyager.firebaseapp.com',
    storageBucket: 'alx-voyager.appspot.com',
    measurementId: 'G-K2HLMJC1GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBcOpFpvjYCnwVa_4nphx5kuzRE3TdZg',
    appId: '1:91542018746:android:00d249d9f6b53eda904083',
    messagingSenderId: '91542018746',
    projectId: 'alx-voyager',
    storageBucket: 'alx-voyager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7cm9jVu_AZq2dQvw9OZ2vc4O71In02bQ',
    appId: '1:91542018746:ios:94f2fc67d8ab8b11904083',
    messagingSenderId: '91542018746',
    projectId: 'alx-voyager',
    storageBucket: 'alx-voyager.appspot.com',
    androidClientId: '91542018746-6scm5tlcv8r5ojutrpa6jok95raplf6p.apps.googleusercontent.com',
    iosClientId: '91542018746-kbj2o1ak11gmjsnjjit6ltum8v8n94i1.apps.googleusercontent.com',
    iosBundleId: 'com.ken.alxVoyager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7cm9jVu_AZq2dQvw9OZ2vc4O71In02bQ',
    appId: '1:91542018746:ios:b96f7e5f8052bb82904083',
    messagingSenderId: '91542018746',
    projectId: 'alx-voyager',
    storageBucket: 'alx-voyager.appspot.com',
    androidClientId: '91542018746-6scm5tlcv8r5ojutrpa6jok95raplf6p.apps.googleusercontent.com',
    iosClientId: '91542018746-7rsem581b28rlgg759ge6p28jil5i4lu.apps.googleusercontent.com',
    iosBundleId: 'com.ken.alxVoyager.RunnerTests',
  );
}
